
setup(name='logging_tree',
      version=0.1,
      url='',
      author='Rusty Howell',
      install_requires=['asciitree'],
      description='Display logging tree for debugging',
      keywords='logging',
      long_description='',
      include_package_data=True,
      zip_safe=False,
      platforms='any',
      classifiers=[
        'Programming Language :: Python',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Development Status :: 4 - Beta',
        'Natural Language :: English',
        'Intended Audience :: Developers',
        'Intended Audience :: System Administrators',
        'Intended Audience :: Telecommunications Industry',
        'License :: OSI Approved :: MIT License',
        'Operating System :: Unix',
        'Operating System :: MacOS',
        ],
      extras_require={'testing': ['iperf3']},
      author_email='rustyhowell@gmail.com',
      license='MIT',
      packages=['logging_tree'])
